Repository openshift/cluster-bootstrap, pull requests merged in 2018-11, with the labels that each got.

#2 start: wait until pods ready
  cmd/cluster-bootstrap/start.go
  pkg/start/status.go
Labels: size/M

#3 Fix Makefile
  Makefile
Labels: lgtm, size/XS

#5 Add image reference
  Dockerfile
  Dockerfile.rhel7
  manifests/image-references
Labels: approved, lgtm, size/S

#4 Remove Travis CI
  .travis.yml
Labels: approved, lgtm, size/S
